#define EG_PHOTON_STRINGIFY3(param) L##param
#define EG_PHOTON_STRINGIFY2(param) EG_PHOTON_STRINGIFY3(#param)
#define EG_PHOTON_STRINGIFY(param) EG_PHOTON_STRINGIFY2(param)
#define EG_PHOTON_CLIENT_VERSION_MAJOR         5
#define EG_PHOTON_CLIENT_VERSION_SERVER_MINOR  0
#define EG_PHOTON_CLIENT_VERSION_CLIENT_MINOR  5
#define EG_PHOTON_CLIENT_VERSION_PATCH_RELEASE 1
#define EG_PHOTON_CLIENT_VERSION EG_PHOTON_STRINGIFY(EG_PHOTON_CLIENT_VERSION_MAJOR) L"." EG_PHOTON_STRINGIFY(EG_PHOTON_CLIENT_VERSION_SERVER_MINOR) L"." EG_PHOTON_STRINGIFY(EG_PHOTON_CLIENT_VERSION_CLIENT_MINOR) L"." EG_PHOTON_STRINGIFY(EG_PHOTON_CLIENT_VERSION_PATCH_RELEASE)
